-- -----------------------------------------------------
-- Table Pais
-- -----------------------------------------------------
CREATE TABLE pais (
    id_pais INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre  VARCHAR2(50) NOT NULL,
    pais_id INTEGER NOT NULL,
    PRIMARY KEY (id_pais)
);

-- -----------------------------------------------------
-- Table Ciudad
-- -----------------------------------------------------
CREATE TABLE ciudad (
    id_ciudad     INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre        VARCHAR2(50) NOT NULL,
    codigo_postal INTEGER NOT NULL,
    id_pais  INTEGER NOT NULL,
    PRIMARY KEY (id_ciudad),
    CONSTRAINT fk_pais_ciudad
    FOREIGN KEY (id_pais) REFERENCES pais (id_pais)
);

-- -----------------------------------------------------
-- Table Tienda
-- -----------------------------------------------------
CREATE TABLE tienda (
    id_tienda INTEGER GENERATED BY DEFAULT AS IDENTITY,
    direccion VARCHAR2(50) NOT NULL,
    PRIMARY KEY (id_tienda)
);

-- -----------------------------------------------------
-- Table Cliente
-- -----------------------------------------------------
CREATE TABLE cliente (
    id_cliente       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre           VARCHAR2(25) NOT NULL,
    apellido         VARCHAR2(25) NOT NULL,
    correo           VARCHAR2(100),
    direccion        VARCHAR2(100) NOT NULL,
    fecha_reg        TIMESTAMP NOT NULL,
    activo           VARCHAR2(5) NOT NULL,
    videoteca_fav    VARCHAR2(100) NOT NULL,
    id_ciudad INTEGER NOT NULL,
    PRIMARY KEY (id_cliente),
    CONSTRAINT fk_ciudad_cliente
    FOREIGN KEY (id_ciudad) REFERENCES ciudad (id_ciudad)
);

-- -----------------------------------------------------
-- Table Empleado
-- -----------------------------------------------------
CREATE TABLE empleado (
    id_empleado      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre           VARCHAR2(25) NOT NULL,
    apellido         VARCHAR2(25) NOT NULL,
    direccion        VARCHAR2(100) NOT NULL,
    correo           VARCHAR2(100) NOT NULL,
    activo           INTEGER NOT NULL,
    usuario          VARCHAR2(25) NOT NULL,
    password         VARCHAR2(100) NOT NULL,
    jefe_tienda      INTEGER NOT NULL,
    id_tienda INTEGER NOT NULL,
    PRIMARY KEY (id_empleado),
    CONSTRAINT id_tienda
    FOREIGN KEY (id_tienda) REFERENCES tienda (id_tienda)
);

-- -----------------------------------------------------
-- Table Clasificacion
-- -----------------------------------------------------
CREATE TABLE clasificacion (
    id_clasificacion INTEGER GENERATED BY DEFAULT AS IDENTITY,
    clasificacion    VARCHAR2(50) NOT NULL,
    PRIMARY KEY (id_clasificacion)
);

-- -----------------------------------------------------
-- Table Categoria
-- -----------------------------------------------------
CREATE TABLE categoria (
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre       VARCHAR2(25),
    PRIMARY KEY (id_categoria)
);

-- -----------------------------------------------------
-- Table Idioma
-- -----------------------------------------------------
CREATE TABLE idioma (
    id_idioma INTEGER GENERATED BY DEFAULT AS IDENTITY,
    idioma    VARCHAR2(25),
    PRIMARY KEY (id_idioma)
);

-- -----------------------------------------------------
-- Table Actor
-- -----------------------------------------------------
CREATE TABLE actor (
    id_actor INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre   VARCHAR2(25) NOT NULL,
    apellido VARCHAR2(25) NOT NULL,
    PRIMARY KEY (id_actor)
);

-- -----------------------------------------------------
-- Table Pelicula
-- -----------------------------------------------------
CREATE TABLE pelicula (
    id_pelicula                    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    titulo                         VARCHAR2(25) NOT NULL,
    descripcion                    VARCHAR2(25) NOT NULL,
    lanzamiento                    VARCHAR2(25) NOT NULL,
    duracion                       REAL NOT NULL,
    dias_renta                     INTEGER NOT NULL,
    costo_renta                    REAL NOT NULL,
    cargo_extra                    REAL NOT NULL,
    idioma_original                VARCHAR2(25) NOT NULL,
    id_clasificacion               INTEGER NOT NULL,
    PRIMARY KEY (id_pelicula),
    CONSTRAINT id_clasificacion
    FOREIGN KEY (id_clasificacion) REFERENCES clasificacion (id_clasificacion)
);

-- -----------------------------------------------------
-- Table Categoria_Pelicula
-- -----------------------------------------------------
CREATE TABLE categoria_pelicula (
    id_categoria INTEGER NOT NULL,
    id_pelicula   INTEGER NOT NULL,
    CONSTRAINT id_categoria
    FOREIGN KEY (id_categoria) REFERENCES categoria (id_categoria),
    CONSTRAINT id_pelicula
    FOREIGN KEY (id_pelicula) REFERENCES pelicula (id_pelicula)

);

-- -----------------------------------------------------
-- Table Pelicula_Actor
-- -----------------------------------------------------
CREATE TABLE pelicula_actor (
    id_pelicula INTEGER NOT NULL,
    id_actor       INTEGER NOT NULL,
    FOREIGN KEY (id_pelicula) REFERENCES pelicula (id_pelicula),
    CONSTRAINT id_actor
    FOREIGN KEY (id_actor) REFERENCES actor (id_actor)
);

-- -----------------------------------------------------
-- Table Traduccion
-- -----------------------------------------------------
CREATE TABLE traduccion (
    id_idioma     INTEGER NOT NULL,
    id_pelicula INTEGER NOT NULL,
    CONSTRAINT id_idioma
    FOREIGN KEY (id_idioma) REFERENCES idioma (id_idioma),
    FOREIGN KEY (id_pelicula) REFERENCES pelicula (id_pelicula)
);

-- -----------------------------------------------------
-- Table Inventario
-- -----------------------------------------------------
CREATE TABLE inventario (
    id_tienda     INTEGER NOT NULL,
    id_pelicula INTEGER NOT NULL,
    FOREIGN KEY (id_tienda) REFERENCES tienda (id_tienda),
    FOREIGN KEY (id_pelicula) REFERENCES pelicula (id_pelicula)
);

-- -----------------------------------------------------
-- Table Renta
-- -----------------------------------------------------
CREATE TABLE renta (
    id_cliente   INTEGER NOT NULL,
    id_empleado INTEGER NOT NULL,
    pago                 REAL NOT NULL,
    fecha_pago           TIMESTAMP NOT NULL,
    fecha_rent           TIMESTAMP NOT NULL,
    fecha_dev            TIMESTAMP NOT NULL,
    id_pelicula INTEGER NOT NULL,
    CONSTRAINT id_cliente
    FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente),
    CONSTRAINT id_empleado
    FOREIGN KEY (id_empleado) REFERENCES empleado (id_empleado),
    FOREIGN KEY (id_pelicula) REFERENCES pelicula (id_pelicula)
);